package kleicreator.editor.frames;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import kleicreator.editor.tabs.Tab;
import kleicreator.editor.tabs.TabItem;
import kleicreator.editor.tabs.TabRecipe;
import kleicreator.data.Mod;
import kleicreator.recipes.Recipe;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;

public class TabRecipeControlForm {
    private JPanel tabRecipeControlPanel;
    private JTable recipeTable;
    private JButton add;
    private JButton remove;

    private final DefaultTableModel tableModel;
    private final EditorMain editorMain;

    public TabRecipeControlForm(JPanel tab, EditorMain editorMain) {
        tab.add(tabRecipeControlPanel);

        this.editorMain = editorMain;

        tableModel = new DefaultTableModel();
        tableModel.addColumn("ID");
        tableModel.addColumn("Result");
        tableModel.addColumn("# of ingredients");
        recipeTable.setModel(tableModel);

        add.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                Recipe r = new Recipe();
                r.result = "id";
                r.ingredients = new ArrayList<String>();
                r.tab = Recipe.RECIPETAB.TOOLS;
                r.tech = Recipe.TECH.NONE;
                Mod.recipes.add(r);
                UpdateTable();
                editorMain.UpdateTabs();
                editorMain.UpdateProjectExplorer();
            }
        });

        remove.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                int selectedIndex = recipeTable.getSelectedRow();
                if (selectedIndex != -1) {
                    Recipe recipe = Mod.recipes.get(selectedIndex);
                    int option = JOptionPane.showConfirmDialog(tab, String.format("Delete '%s'?", recipe.id), "Delete recipe?", JOptionPane.OK_CANCEL_OPTION);
                    if (option == 0) {
                        for (Iterator<Tab> iterator = editorMain.tabs.iterator(); iterator.hasNext(); ) {
                            Tab tab = iterator.next();
                            if (tab instanceof TabItem) {
                                if (((TabRecipe) tab).recipe == recipe) {
                                    iterator.remove();
                                }
                            }
                        }
                        Mod.recipes.remove(selectedIndex);
                        UpdateTable();
                        editorMain.UpdateTabs();
                        editorMain.UpdateProjectExplorer();
                    }
                } else {
                    JOptionPane.showMessageDialog(tab, "No recipe selected", "No recipe select", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
    }

    public void UpdateTable() {
        tableModel.setRowCount(0);
        for (Recipe recipe : Mod.recipes) {
            tableModel.addRow(new String[]{recipe.id, recipe.result, String.valueOf(recipe.ingredients.size())});
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        tabRecipeControlPanel = new JPanel();
        tabRecipeControlPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        recipeTable = new JTable();
        recipeTable.setAutoCreateRowSorter(false);
        recipeTable.setFillsViewportHeight(false);
        tabRecipeControlPanel.add(recipeTable, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        tabRecipeControlPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        add = new JButton();
        add.setText("Add");
        panel1.add(add, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        remove = new JButton();
        remove.setText("Button");
        panel1.add(remove, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return tabRecipeControlPanel;
    }

}
