package kleicreator.items;

import kleicreator.modloader.Mod;

import javax.swing.*;
import java.util.Arrays;
import java.util.List;

public class AllItems {

    public static Item SelectFromAllItems(JPanel panel) {
        List<Item> items = Mod.GetAllItems();
        Object[] objArray = items.toArray();
        Object selection = JOptionPane.showInputDialog(panel, "Select New Item", "Select New Item", JOptionPane.QUESTION_MESSAGE, null, objArray, 0);
        for(Item i : items){
            if(i.itemName.equals(selection.toString())){
                return i;
            }
        }
        return items.get(0);
    }

    // Maybe load this in from a file or similar?
    public static List<Item> allItems = Arrays.asList(
            new Item("Abigail's Flower", "abigail_flower"),
            new Item("Applied Horticulture", "book_gardening"),
            new Item("Ashes", "ash"),
            new Item("Axe", "axe"),
            new Item("Backpack", "backpack"),
            new Item("Bacon and Eggs", "baconeggs"),
            new Item("Ball and Cup", "trinket_7"),
            new Item("Bat Bat", "batbat"),
            new Item("Batilisk Wing", "batwing"),
            new Item("Beard Hair", "beardhair"),
            new Item("Beardling", "rabbit"),
            new Item("Bee", "bee"),
            new Item("Bee Mine", "beemine"),
            new Item("Beefalo Hat", "beefalohat"),
            new Item("Beefalo Horn", "horn"),
            new Item("Beefalo Wool", "beefalowool"),
            new Item("Beekeeper Hat", "beehat"),
            new Item("Belt of Hunger", "armorslurper"),
            new Item("Berries", "berries"),
            new Item("Berry Bush", "dug_berrybush"),
            new Item("Birds of the World", "book_birds"),
            new Item("Bird Trap", "birdtrap"),
            new Item("Blow Dart", "blowdart_pipe"),
            new Item("Blue Cap", "blue_cap"),
            new Item("Blue Gem", "bluegem"),
            new Item("Blueprint", "<name>_blueprint"),
            new Item("Boards", "boards"),
            new Item("Boomerang", "boomerang"),
            new Item("Box Thing", "teleportato_box"),
            new Item("Braised Eggplant", "eggplant_cooked"),
            new Item("Breezy Vest", "trunkvest_summer"),
            new Item("Broken Shell", "slurtle_shellpieces"),
            new Item("Bug Net", "bugnet"),
            new Item("Bunny Puff", "manrabbit_tail"),
            new Item("Bush Hat", "bushhat"),
            new Item("Butter", "butter"),
            new Item("Butter Muffin", "butterflymuffin"),
            new Item("Butterfly", "butterfly"),
            new Item("Butterfly Wings", "butterflywings"),
            new Item("Carrot", "carrot"),
            new Item("Carrot Seeds", "carrot_seeds"),
            new Item("Cave Banana", "cave_banana"),
            new Item("Cave Rock Turf", "turf_underrock"),
            new Item("Charcoal", "charcoal"),
            new Item("Carpeted Flooring", "turf_carpetfloor"),
            new Item("Checkerboard Flooring", "turf_checkerfloor"),
            new Item("Chilled Amulet", "blueamulet"),
            new Item("Cobblestones", "turf_road"),
            new Item("Codex Umbra", "waxwelljournal"),
            new Item("Construction Amulet", "greenamulet"),
            new Item("Cooked Batilisk Wing", "batwing_cooked"),
            new Item("Cooked Blue Cap", "blue_cap_cooked"),
            new Item("Cooked Cave Banana", "cave_banana_cooked"),
            new Item("Cooked Egg", "bird_egg_cooked"),
            new Item("Cooked Eel", "eel_cooked"),
            new Item("Cooked Fish", "fish_cooked"),
            new Item("Cooked Frog Legs", "froglegs_cooked"),
            new Item("Cooked Green Cap", "green_cap_cooked"),
            new Item("Cooked Leafy Meat", "plantmeat_cooked"),
            new Item("Cooked Mandrake", "mandrake"),
            new Item("Cooked Meat", "cookedmeat"),
            new Item("Cooked Monster Meat", "cookedmonstermeat"),
            new Item("Cooked Morsel", "cookedsmallmeat"),
            new Item("Cooked Red Cap", "red_cap_cooked"),
            new Item("Compass", "compass"),
            new Item("Corn", "corn"),
            new Item("Corn Seeds", "corn_seeds"),
            new Item("Crank Thing", "teleportato_crank"),
            new Item("Crimson Feather", "feather_robin"),
            new Item("Crow", "crow"),
            new Item("Crow Feather", "feather_crow"),
            new Item("Cut Grass", "cutgrass"),
            new Item("Cut Reeds", "cutreeds"),
            new Item("Cut Stone", "cutstone"),
            new Item("Dapper Vest", "sweatervest"),
            new Item("Dark Petals", "petals_evil"),
            new Item("Dark Sword", "nightsword"),
            new Item("Deconstruction Staff", "greenstaff"),
            new Item("Deerclops Eyeball", "deerclops_eyeball"),
            new Item("Dessicated Tentacle", "trinket_12"),
            new Item("Divining Rod", "diviningrod"),
            new Item("Dragon Fruit", "dragonfruit"),
            new Item("Dragon Fruit Seeds", "dragonfruit_seeds"),
            new Item("Dragonpie", "dragonpie"),
            new Item("Drumstick", "drumstick"),
            new Item("Durian", "durian"),
            new Item("Durian Seeds", "durian_seeds"),
            new Item("Eel", "eel"),
            new Item("Egg", "bird_egg"),
            new Item("Eggplant", "eggplant"),
            new Item("Eggplant Seeds", "eggplant_seeds"),
            new Item("Extra Smelly Durian", "durian_cooked"),
            new Item("Eye Bone", "chester_eyebone"),
            new Item("Fake Kazoo", "trinket_2"),
            new Item("Feather Hat", "featherhat"),
            new Item("Fire Dart", "blowdart_fire"),
            new Item("Fire Staff", "firestaff"),
            new Item("Fireflies", "fireflies"),
            new Item("Fish", "fish"),
            new Item("Fish Tacos", "fishtacos"),
            new Item("Fishing Rod", "fishingrod"),
            new Item("Fishsticks", "fishsticks"),
            new Item("Fist Full of Jam", "jammypreserves"),
            new Item("Fleshy Bulb", "lureplantbulb"),
            new Item("Flint", "flint"),
            new Item("Football Helmet", "footballhat"),
            new Item("Foliage", "foliage"),
            new Item("Forest Turf", "turf_forest"),
            new Item("Frazzled Wires", "trinket_6"),
            new Item("Fried Drumstick", "drumstick_cooked"),
            new Item("Fried Tallbird Egg", "tallbirdegg_cooked"),
            new Item("Frog Legs", "froglegs"),
            new Item("Froggle Bunwich", "frogglebunwich"),
            new Item("Fruit Medley", "fruitmedley"),
            new Item("Fungal Turf (Blue)", "turf_fungus"),
            new Item("Fungal Turf (Red)", "turf_fungus"),
            new Item("Fungal Turf (Green)", "turf_fungus"),
            new Item("Fur Roll", "bedroll_furry"),
            new Item("Garland", "flowerhat"),
            new Item("Gears", "gears"),
            new Item("Glow Berry", "wormlight"),
            new Item("Gnome", "trinket_4"),
            new Item("Gold Nugget", "goldnugget"),
            new Item("Gord's Knot", "trinket_3"),
            new Item("Grass Suit", "armorgrass"),
            new Item("Grass Tuft", "grass"),
            new Item("Grass Turf", "turf_grass"),
            new Item("Green Gem", "greengem"),
            new Item("Green Cap", "green_cap"),
            new Item("Guano", "guano"),
            new Item("Guano Turf", "turf_cave"),
            new Item("Guardian's Horn", "minotaurhorn"),
            new Item("Gunpowder", "gunpowder"),
            new Item("Ham Bat", "hambat"),
            new Item("Hammer", "hammer"),
            new Item("Hardened Rubber Bung", "trinket_8"),
            new Item("Hatching Tallbird Egg", "tallbirdegg_cracked"),
            new Item("Hay Wall", "wall_hay_item"),
            new Item("Healing Salve", "healingsalve"),
            new Item("Thermal Stone", "heatrock"),
            new Item("Honey", "honey"),
            new Item("Honey Ham", "honeyham"),
            new Item("Honey Nuggets", "honeynuggets"),
            new Item("Honey Poultice", "bandage"),
            new Item("Honeycomb", "honeycomb"),
            new Item("Hot Pumpkin", "pumpkin_cooked"),
            new Item("Hound's Tooth", "houndstooth"),
            new Item("Houndius Shootius", "eyeturret_item"),
            new Item("Ice Staff", "icestaff"),
            new Item("Jerky", "meat_dried"),
            new Item("Kabobs", "kabobs"),
            new Item("Killer Bee", "killerbee"),
            new Item("Koalefant Trunk", "trunk_summer"),
            new Item("Koalefant Trunk Steak", "trunk_cooked"),
            new Item("Krampus Sack", "krampus_sack"),
            new Item("Lantern", "lantern"),
            new Item("The Lazy Forager", "orangeamulet"),
            new Item("Lichen", "cutlichen"),
            new Item("Leafy Meat", "plantmeat"),
            new Item("Life Giving Amulet", "amulet"),
            new Item("Light Bulb", "lightbulb"),
            new Item("Living Log", "livinglog"),
            new Item("Log", "log"),
            new Item("Log Suit", "armorwood"),
            new Item("Lucy the Axe", "lucy"),
            new Item("Luxury Axe", "goldenaxe"),
            new Item("Lying Robot", "trinket_11"),
            new Item("Magiluminescence", "yellowamulet"),
            new Item("Mandrake", "mandrake"),
            new Item("Mandrake Soup", "mandrakesoup"),
            new Item("Manure", "poop"),
            new Item("Marble", "marble"),
            new Item("Marble Suit", "armormarble"),
            new Item("Marsh Bush", "dug_marsh_bush"),
            new Item("Marsh Turf", "turf_marsh"),
            new Item("Meat", "meat"),
            new Item("Meatballs", "meatballs"),
            new Item("Meaty Stew", "bonestew"),
            new Item("Melty Marbles", "trinket_1"),
            new Item("Metal Potato Thing", "teleportato_potato"),
            new Item("Miner Hat", "minerhat"),
            new Item("Mismatched Buttons", "trinket_9"),
            new Item("Monster Jerky", "monstermeat_dried"),
            new Item("Monster Lasagna", "monsterlasagna"),
            new Item("Monster Meat", "monstermeat"),
            new Item("Morsel", "smallmeat"),
            new Item("Mosquito", "mosquito"),
            new Item("Mosquito Sack", "mosquitosack"),
            new Item("Mud Turf", "turf_mud"),
            new Item("Night Armour", "armor_sanity"),
            new Item("Nightmare Fuel", "nightmarefuel"),
            new Item("Nightmare Amulet", "purpleamulet"),
            new Item("Nitre", "nitre"),
            new Item("On Tentacles", "book_tentacles"),
            new Item("One-man Band", "onemanband"),
            new Item("Opulent Pickaxe", "goldenpickaxe"),
            new Item("Orange Gem", "orangegem"),
            new Item("Pan Flute", "panflute"),
            new Item("Papyrus", "papyrus"),
            new Item("Petals", "petals"),
            new Item("Pickaxe", "pickaxe"),
            new Item("Pick/Axe", "multitool_axe_pickaxe"),
            new Item("Pierogi", "perogies"),
            new Item("Pig Skin", "pigskin"),
            new Item("Piggyback", "piggyback"),
            new Item("Pile o' Balloons", "balloons_empty"),
            new Item("Pine Cone", "pinecone"),
            new Item("Pitchfork", "pitchfork"),
            new Item("Pomegranate", "pomegranate"),
            new Item("Pomegranate Seeds", "pomegranate_seeds"),
            new Item("Popcorn", "corn_cooked"),
            new Item("Powdercake", "powcake"),
            new Item("Prepared Dragon Fruit", "dragonfruit_cooked"),
            new Item("Puffy Vest", "trunkvest_winter"),
            new Item("Pumpkin", "pumpkin"),
            new Item("Pumpkin Seeds", "pumpkin_seeds"),
            new Item("Pumpkin Cookie", "pumpkincookie"),
            new Item("Pumpkin Lantern", "pumpkin_lantern"),
            new Item("Purple Gem", "purplegem"),
            new Item("Rabbit", "rabbit"),
            new Item("Rabbit Earmuffs", "earmuffshat"),
            new Item("Ratatouille", "ratatouille"),
            new Item("Razor", "razor"),
            new Item("Red Gem", "redgem"),
            new Item("Red Cap", "red_cap"),
            new Item("Redbird", "robin"),
            new Item("Regal Shovel", "goldenshovel"),
            new Item("Ring Thing", "teleportato_ring"),
            new Item("Roasted Berries", "berries_cooked"),
            new Item("Roasted Carrot", "carrot_cooked"),
            new Item("Rocks", "rocks"),
            new Item("Rocky Turf", "turf_rocky"),
            new Item("Rope", "rope"),
            new Item("Rot", "spoiled_food"),
            new Item("Rotten Egg", "rottenegg"),
            new Item("Dug Sapling", "sapling"),
            new Item("Savanna Turf", "turf_savanna"),
            new Item("Second-hand Dentures", "trinket_10"),
            new Item("Seeds", "seeds"),
            new Item("Sewing Kit", "sewing_kit"),
            new Item("Shelmet", "slurtlehat"),
            new Item("Shovel", "shovel"),
            new Item("Silk", "silk"),
            new Item("Sleep Dart", "blowdart_sleep"),
            new Item("Sleepytime Stories", "book_sleep"),
            new Item("Sliced Pomegranate", "pomegranate_cooked"),
            new Item("Slimey Turf", "turf_sinkhole"),
            new Item("Slurper Pelt", "slurper_pelt"),
            new Item("Slurtle Slime", "slurtleslime"),
            new Item("Small Jerky", "smallmeat_dried"),
            new Item("Snowbird", "robin_winter"),
            new Item("Azure Feather", "feather_robin_winter"),
            new Item("Snurtle Shell Armour", "armorsnurtleshell"),
            new Item("Spear", "spear"),
            new Item("Spider Eggs", "spidereggsack"),
            new Item("Spider Gland", "spidergland"),
            new Item("Spiderhat", "spiderhat"),
            new Item("Star Caller's Staff", "stafflight"),
            new Item("Stinger", "stinger"),
            new Item("Stone Wall", "wall_stone_item"),
            new Item("Straw Hat", "strawhat"),
            new Item("Straw Roll", "bedroll_straw"),
            new Item("Stuffed Eggplant", "stuffedeggplant"),
            new Item("Taffy", "taffy"),
            new Item("Tallbird Egg", "tallbirdegg"),
            new Item("Tam o' Shanter", "walrushat"),
            new Item("Telelocator Staff", "telestaff"),
            new Item("Tentacle Spike", "tentaclespike"),
            new Item("Tentacle Spots", "tentaclespots"),
            new Item("The End is Nigh!", "book_brimstone"),
            new Item("The Lazy Explorer", "orangestaff"),
            new Item("Thulecite", "thulecite"),
            new Item("Thulecite Crown", "ruinshat"),
            new Item("Thulecite Fragments", "thulecite_pieces"),
            new Item("Thulecite Club", "ruins_bat"),
            new Item("Thulecite Medallion", "nightmare_timepiece"),
            new Item("Thulecite Suit", "armorruins"),
            new Item("Thulecite Wall", "wall_ruins_item"),
            new Item("Tiny Rocketship", "trinket_5"),
            new Item("Toasted Seeds", "seeds_cooked"),
            new Item("Tooth Trap", "trap_teeth"),
            new Item("Top Hat", "tophat"),
            new Item("Torch", "torch"),
            new Item("Trap", "trap"),
            new Item("Turkey Dinner", "turkeydinner"),
            new Item("Twigs", "twigs"),
            new Item("Umbrella", "umbrella"),
            new Item("Unagi", "unagi"),
            new Item("Walking Cane", "cane"),
            new Item("Waffles", "waffles"),
            new Item("Walrus Tusk", "walrus_tusk"),
            new Item("Wet Goop", "wetgoop"),
            new Item("Winter Hat", "winterhat"),
            new Item("Winter Rabbit", "rabbit"),
            new Item("Winter Koalefant Trunk", "trunk_winter"),
            new Item("Willow's Lighter", "lighter"),
            new Item("Wood Wall", "wall_wood_item"),
            new Item("Wooden Flooring", "turf_woodfloor"),
            new Item("Yellow Gem", "yellowgem")
    );

}
