package kleicreator.frames;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class ExportDialog {
    private JPanel exportWindowFrame;
    private JProgressBar exportProgressBar;
    private JLabel exportingLabel;

    public JPanel getExportWindowFrame() {
        return exportWindowFrame;
    }

    public JProgressBar getExportProgressBar() {
        return exportProgressBar;
    }

    public JLabel getExportingLabel() {
        return exportingLabel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        exportWindowFrame = new JPanel();
        exportWindowFrame.setLayout(new GridLayoutManager(2, 1, new Insets(30, 30, 30, 30), -1, -1));
        exportProgressBar = new JProgressBar();
        exportProgressBar.setValue(0);
        exportWindowFrame.add(exportProgressBar, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        exportingLabel = new JLabel();
        exportingLabel.setText("Exporting...");
        exportWindowFrame.add(exportingLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return exportWindowFrame;
    }
}
